version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/" 
    schedule:
      interval: "daily"
    target-branch: "develop"
      
  - package-ecosystem: "npm" 
    directory: "/app/dashboard/" 
    schedule:
      interval: "daily"
    target-branch: "develop"
      
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "daily"
    target-branch: "develop"
